export type Role = {
  id: string;
  role: string;
  group: string;
  accessLevel: string;
  users: number;
  permissionSets: string[];
  lastReview: string;
  owner: string;
  status: "Active" | "Needs review";
};

export const roles: Role[] = [
  {
    id: "owner-role-id",
    role: "Owner",
    group: "Needs review",
    accessLevel: "Full",
    users: 2,
    permissionSets: ["Users", "Settings", "Billing", "Reports", "Integrations", "Audit Logs"],
    lastReview: "Apr 12, 2025",
    owner: "System",
    status: "Needs review",
  },
  {
    id: "admin-role-id",
    role: "Admin",
    group: "Needs review",
    accessLevel: "Full",
    users: 5,
    permissionSets: ["Users", "Settings", "Reports", "Billing", "Integrations"],
    lastReview: "Apr 15, 2025",
    owner: "Jane Doe",
    status: "Needs review",
  },
  {
    id: "manager-role-id",
    role: "Manager",
    group: "Needs review",
    accessLevel: "Scoped",
    users: 12,
    permissionSets: ["Users", "Reports", "Projects", "Tasks"],
    lastReview: "Apr 18, 2025",
    owner: "Jane Doe",
    status: "Needs review",
  },
  {
    id: "support-role-id",
    role: "Support",
    group: "System roles",
    accessLevel: "Scoped",
    users: 8,
    permissionSets: ["Users", "Tickets", "Reports", "Knowledge Base"],
    lastReview: "May 1, 2025",
    owner: "System",
    status: "Active",
  },
  {
    id: "analyst-role-id",
    role: "Analyst",
    group: "System roles",
    accessLevel: "Scoped",
    users: 6,
    permissionSets: ["Reports", "Analytics", "Dashboards", "Exports"],
    lastReview: "May 5, 2025",
    owner: "System",
    status: "Active",
  },
  {
    id: "guest-role-id",
    role: "Guest",
    group: "System roles",
    accessLevel: "Read only",
    users: 14,
    permissionSets: ["Reports", "Dashboards"],
    lastReview: "May 6, 2025",
    owner: "System",
    status: "Active",
  },
  {
    id: "service-role-id",
    role: "Service",
    group: "System roles",
    accessLevel: "API access",
    users: 3,
    permissionSets: ["Integrations", "API Keys", "Webhooks", "Logs"],
    lastReview: "Apr 22, 2025",
    owner: "System",
    status: "Active",
  },
  {
    id: "billing-role-id",
    role: "Billing",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 3,
    permissionSets: ["Billing", "Invoices", "Payments", "Reports"],
    lastReview: "Apr 28, 2025",
    owner: "Alex Kim",
    status: "Active",
  },
  {
    id: "marketing-role-id",
    role: "Marketing",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 9,
    permissionSets: ["Users", "Reports", "Campaigns", "Analytics", "Exports"],
    lastReview: "May 2, 2025",
    owner: "Alex Kim",
    status: "Active",
  },
  {
    id: "developer-role-id",
    role: "Developer",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 10,
    permissionSets: ["Repos", "Deployments", "Settings", "API Keys", "Logs"],
    lastReview: "May 3, 2025",
    owner: "Chris Lee",
    status: "Active",
  },
  {
    id: "project-lead-role-id",
    role: "Project Lead",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 7,
    permissionSets: ["Projects", "Tasks", "Reports", "Users", "Settings"],
    lastReview: "Apr 30, 2025",
    owner: "Chris Lee",
    status: "Active",
  },
  {
    id: "finance-viewer-role-id",
    role: "Finance Viewer",
    group: "Custom roles",
    accessLevel: "Read only",
    users: 4,
    permissionSets: ["Billing", "Reports", "Invoices", "Dashboards"],
    lastReview: "May 7, 2025",
    owner: "Jane Doe",
    status: "Active",
  },
];
